#### Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [1]:
import numpy as np

In [2]:
def Vandermonde(l,N=None,increasing=False):
    if(N==None):
        N=len(l)
    result=[]
    for num in l:
        insert=[]
        for i in range(N):
            insert.append(num**i)
        result.append(insert)
    if(increasing==False):
        result1=[]
        for lists in result:
            result1.append(lists[::-1])
        return np.array(result1)
    else:
        return np.array(result)

In [3]:
#1
Vandermonde(l=[2,3,4,5],N=5)

array([[ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [4]:
#2 increasing=False by default
l=[1,2,3,4]
Vandermonde(l)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [5]:
#3 increasing=True
l=[1,2,3,4]
Vandermonde(l,increasing=True)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

In [6]:
#4 increasing=True and N
l=[2,3,4,5]
Vandermonde(l,N=6,increasing=True)

array([[   1,    2,    4,    8,   16,   32],
       [   1,    3,    9,   27,   81,  243],
       [   1,    4,   16,   64,  256, 1024],
       [   1,    5,   25,  125,  625, 3125]])

####  Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3

In [7]:
l=[2,3,4,5,6,7,8,9,11,12,13]
def moving_average(l,k):
    result=[]
    for i in range(len(l)):
        result.append(round(sum(np.array(l)[i:i+k])/k,2) )   
    return result
        

In [8]:
moving_average(l,k=3)

[3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.33, 10.67, 12.0, 8.33, 4.33]